const mongoose = require('mongoose');

const MONGODB_URI = 'mongodb+srv://salman:4lanHyMRdCrtXDJ7@sign365.nglnioh.mongodb.net/booran_warranty?retryWrites=true&w=majority';

async function run() {
  console.log('Connecting to MongoDB Atlas...');
  await mongoose.connect(MONGODB_URI);
  console.log('Connected successfully!');

  const db = mongoose.connection.db;

  // Check if collection exists
  const collections = await db.listCollections({ name: 'loan_agreements' }).toArray();
  console.log('Existing collections matching loan_agreements:', collections.length);

  const sampleAgreements = [
    {
      id: 'lagr_cranbourne_001',
      agreementNumber: 'BMG-CRANBOURNE-2026-0148',
      siteId: 'site_cranbourne_byd',
      siteName: 'Booran BYD Cranbourne',
      roNumber: 'RO-48021',
      purpose: 'SERVICE_LOANER',
      status: 'ACTIVE',
      customer: {
        name: 'David Okonkwo',
        dob: '1988-06-14',
        mobile: '+61 412 000 006',
        email: 'david.okonkwo@gmail.com',
        residentialAddress: '42 Station St, Cranbourne VIC 3977',
        licenceNumber: '98421098',
        licenceState: 'VIC',
        licenceExpiry: '2028-11-20',
        licenceClass: 'C',
        licenceSighted: true,
      },
      vehicle: {
        vin: 'LGXCE4C86P0019283',
        rego: 'BMG214',
        make: 'Toyota',
        model: 'RAV4 Cruiser',
        year: 2024,
        colour: 'Pearl White',
        stockNumber: 'LN-9842',
      },
      loanStartDateTime: new Date(Date.now() - 3600000 * 5).toISOString(),
      dueBackDateTime: new Date(Date.now() + 3600000 * 2).toISOString(),
      dailyKmCap: 50,
      excessKmRate: 0.50,
      basicInsuranceExcess: 2500,
      outbound: {
        odometerOut: 12485,
        fuelLevelOutPercent: 75,
        damageNotes: 'Minor scuff on rear left wheel arch.',
        photos: {
          front: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80',
        },
        issuedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
        issuedByStaffId: 'usr_tech_1',
        issuedByStaffName: 'Jake Smith',
      },
      signatures: {
        borrowerSignatureDataUrl: 'data:image/png;base64,sample_signature',
        borrowerSignedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
        readAndAgreed: true,
        electronicConsent: true,
        privacyNoticeAcknowledged: true,
        marketingConsent: false,
        staffSignedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
      },
      templateVersion: 'v1.0-2026',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'lagr_cranbourne_002',
      agreementNumber: 'BMG-CRANBOURNE-2026-0147',
      siteId: 'site_cranbourne_byd',
      siteName: 'Booran BYD Cranbourne',
      roNumber: 'RO-99120',
      purpose: 'TEST_DRIVE',
      status: 'OVERDUE',
      customer: {
        name: 'Priya Sharma',
        dob: '1995-02-18',
        mobile: '+61 422 111 888',
        email: 'priya.sharma@outlook.com',
        residentialAddress: '15 High St, Berwick VIC 3806',
        licenceNumber: '44102941',
        licenceState: 'VIC',
        licenceExpiry: '2027-04-12',
        licenceClass: 'C',
        licenceSighted: true,
      },
      vehicle: {
        vin: 'LGXCE4C86P0022391',
        rego: 'BMG198',
        make: 'Kia',
        model: 'Sportage GT-Line',
        year: 2024,
        colour: 'Gravity Grey',
        stockNumber: 'LN-7710',
      },
      loanStartDateTime: new Date(Date.now() - 86400000).toISOString(),
      dueBackDateTime: new Date(Date.now() - 3600000 * 4).toISOString(), // 4h overdue
      dailyKmCap: 50,
      excessKmRate: 0.50,
      basicInsuranceExcess: 2500,
      outbound: {
        odometerOut: 18450,
        fuelLevelOutPercent: 90,
        damageNotes: 'Clean, no existing damage observed.',
        photos: {},
        issuedAt: new Date(Date.now() - 86400000).toISOString(),
        issuedByStaffId: 'usr_admin_1',
        issuedByStaffName: 'Sarah Jenkins',
      },
      signatures: {
        borrowerSignatureDataUrl: 'data:image/png;base64,sample_signature',
        borrowerSignedAt: new Date(Date.now() - 86400000).toISOString(),
        readAndAgreed: true,
        electronicConsent: true,
        privacyNoticeAcknowledged: true,
        marketingConsent: true,
      },
      templateVersion: 'v1.0-2026',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'lagr_dandenong_001',
      agreementNumber: 'BMG-DANDENONG-2026-0044',
      siteId: 'site_dandenong_multi',
      siteName: 'Booran Dandenong Multi-Franchise',
      roNumber: 'RO-30219',
      purpose: 'SERVICE_LOANER',
      status: 'ACTIVE',
      customer: {
        name: 'James Wilson',
        dob: '1982-10-30',
        mobile: '+61 433 999 222',
        email: 'james.wilson@buildcorp.com.au',
        residentialAddress: '88 Lonsdale St, Dandenong VIC 3175',
        licenceNumber: '11029384',
        licenceState: 'VIC',
        licenceExpiry: '2029-08-01',
        licenceClass: 'C',
        licenceSighted: true,
      },
      vehicle: {
        vin: 'JM0KF4W2800192834',
        rego: 'BMG175',
        make: 'Mazda',
        model: 'CX-5 Akera',
        year: 2023,
        colour: 'Soul Red',
        stockNumber: 'LN-6020',
      },
      loanStartDateTime: new Date(Date.now() - 3600000 * 3).toISOString(),
      dueBackDateTime: new Date(Date.now() + 3600000 * 3).toISOString(),
      dailyKmCap: 50,
      excessKmRate: 0.50,
      basicInsuranceExcess: 2500,
      outbound: {
        odometerOut: 32100,
        fuelLevelOutPercent: 100,
        damageNotes: 'Stone chips on front bumper.',
        photos: {},
        issuedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
        issuedByStaffId: 'usr_tech_2',
        issuedByStaffName: 'Liam Miller',
      },
      signatures: {
        borrowerSignatureDataUrl: 'data:image/png;base64,sample_signature',
        borrowerSignedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
        readAndAgreed: true,
        electronicConsent: true,
        privacyNoticeAcknowledged: true,
        marketingConsent: false,
        staffSignedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
      },
      templateVersion: 'v1.0-2026',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'lagr_berwick_001',
      agreementNumber: 'BMG-BERWICK-2026-0089',
      siteId: 'site_berwick_nissan',
      siteName: 'Booran Nissan Berwick',
      roNumber: 'RO-55219',
      purpose: 'SERVICE_LOANER',
      status: 'DUE_SOON',
      customer: {
        name: 'Michael Chen',
        dob: '1990-09-12',
        mobile: '+61 411 333 777',
        email: 'michael.chen@techmail.com.au',
        residentialAddress: '29 Clyde Rd, Berwick VIC 3806',
        licenceNumber: '88392019',
        licenceState: 'VIC',
        licenceExpiry: '2028-05-15',
        licenceClass: 'C',
        licenceSighted: true,
      },
      vehicle: {
        vin: 'JN1TBNT32A0091823',
        rego: 'BMG302',
        make: 'Nissan',
        model: 'X-Trail Ti',
        year: 2024,
        colour: 'Diamond Black',
        stockNumber: 'LN-8812',
      },
      loanStartDateTime: new Date(Date.now() - 3600000 * 6).toISOString(),
      dueBackDateTime: new Date(Date.now() + 1800000).toISOString(), // Due in 30 minutes
      dailyKmCap: 50,
      excessKmRate: 0.50,
      basicInsuranceExcess: 2500,
      outbound: {
        odometerOut: 14200,
        fuelLevelOutPercent: 100,
        damageNotes: 'Clean pre-delivery inspection.',
        photos: {},
        issuedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
        issuedByStaffId: 'usr_advisor_2',
        issuedByStaffName: 'Chloe Taylor',
      },
      signatures: {
        borrowerSignatureDataUrl: 'data:image/png;base64,sample_signature',
        borrowerSignedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
        readAndAgreed: true,
        electronicConsent: true,
        privacyNoticeAcknowledged: true,
        marketingConsent: false,
      },
      templateVersion: 'v1.0-2026',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'lagr_cheltenham_001',
      agreementNumber: 'BMG-CHELTENHAM-2026-0012',
      siteId: 'site_cheltenham_mg',
      siteName: 'Booran MG Cheltenham',
      roNumber: 'RO-18920',
      purpose: 'SERVICE_LOANER',
      status: 'RETURNED',
      customer: {
        name: 'Sarah Connor',
        dob: '1985-11-23',
        mobile: '+61 400 888 123',
        email: 'sarah.c@skytech.net.au',
        residentialAddress: '102 Nepean Hwy, Cheltenham VIC 3192',
        licenceNumber: '29384710',
        licenceState: 'VIC',
        licenceExpiry: '2027-10-10',
        licenceClass: 'C',
        licenceSighted: true,
      },
      vehicle: {
        vin: 'LSJGB83W5NZ489123',
        rego: '1WR2XP',
        make: 'MG',
        model: 'ZS EV Essence',
        year: 2024,
        colour: 'Dover White',
        stockNumber: 'LN-4411',
      },
      loanStartDateTime: new Date(Date.now() - 86400000 * 2).toISOString(),
      dueBackDateTime: new Date(Date.now() - 3600000 * 2).toISOString(),
      dailyKmCap: 50,
      excessKmRate: 0.50,
      basicInsuranceExcess: 2500,
      outbound: {
        odometerOut: 8500,
        fuelLevelOutPercent: 100,
        damageNotes: 'Clean, no existing damage.',
        photos: {},
        issuedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
        issuedByStaffId: 'usr_tech_3',
        issuedByStaffName: 'Mark Vance',
      },
      inbound: {
        odometerIn: 8640,
        fuelLevelInPercent: 95,
        returnedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
        receivedByStaffId: 'usr_tech_3',
        receivedByStaffName: 'Mark Vance',
        damageIdentified: false,
        incidentReported: false,
        totalKmTravelled: 140,
        allowableKm: 100,
        excessKm: 40,
        excessKmChargeAmount: 20.00,
        selectedExcessBand: 'Basic Excess ($2,500)',
      },
      signatures: {
        borrowerSignatureDataUrl: 'data:image/png;base64,sample_signature',
        borrowerSignedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
        readAndAgreed: true,
        electronicConsent: true,
        privacyNoticeAcknowledged: true,
        marketingConsent: false,
      },
      templateVersion: 'v1.0-2026',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  const collection = db.collection('loan_agreements');
  for (const item of sampleAgreements) {
    await collection.updateOne(
      { id: item.id },
      { $setOnInsert: item },
      { upsert: true }
    );
  }

  const finalCount = await collection.countDocuments();
  console.log(`Successfully seeded! 'loan_agreements' collection now has ${finalCount} documents in MongoDB Atlas!`);
  await mongoose.disconnect();
}

run().catch((err) => {
  console.error('Error seeding loan agreements:', err);
  process.exit(1);
});
